use company;

-- 1) write a query That Displays the SSN, Fname, Lname, Plocation 
--    of all employees working on projects managed by the department whose manager is "Frank Wong"






-- 2) Show the SSN, Fname, Lname from the Employee table and the Dependent_name and relationship from the dependent table
--    for employees working on projects located in "Bellair"





-- 3) Create an update trigger for the employee table that:
--    will not allow an employee to have a salary greater than their supervisor (keep salary as is in this case) 
--    nor accept a new salary that is less than their current salary (keep salary as is in this case)
   
   
   
   
-- 4) Convert point 1) to its equivalent relational algebra expression
--    note: you are allowed to solve this one by hand, scan it, and upload it as a second attachment
--    you can open this file on workbench to write your script and test it
--    and you can open it on word to use the equation tool for point 4) if you are comfortable doing that